language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install: 
    - pip install -r dev_requirements.txt
    - pip install coveralls
script: 
    - nosetests --cover-package=deepstreampy --with-coverage
    - behave
after_success: coveralls
